
title: tingle tangle
author: deathbeds
email: tony.fast@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  tangling documents to python programs.

execute:
  execute_notebooks: "off"